# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-05-03 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ame', models.CharField(max_length=30)),
                ('a_ddress', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=20)),
                ('p_wd', models.CharField(max_length=20)),
            ],
        ),
    ]
