# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-05-07 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileuploadmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ame', models.CharField(max_length=20)),
                ('f_ile', models.ImageField(upload_to='app1/static/web/images')),
                ('d_escription', models.CharField(max_length=100)),
            ],
        ),
    ]
