# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-05-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_fileuploadmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuploadmodel',
            old_name='n_ame',
            new_name='i_tem',
        ),
        migrations.RemoveField(
            model_name='fileuploadmodel',
            name='d_escription',
        ),
        migrations.AddField(
            model_name='fileuploadmodel',
            name='p_rice',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
