# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-05-07 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210507_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileuploadmodel',
        ),
    ]
