# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-05-07 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delete_fileuploadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_tem', models.CharField(max_length=20)),
                ('p_rice', models.IntegerField()),
                ('f_ile', models.ImageField(upload_to='app1/static')),
            ],
        ),
    ]
