# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-05-08 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_recipemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='f_ile',
            field=models.ImageField(upload_to='app1/static/'),
        ),
    ]
