# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-05-11 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210508_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_tem', models.CharField(max_length=20)),
                ('p_rice', models.IntegerField()),
                ('q_uantity', models.IntegerField()),
                ('answer', models.IntegerField(null=True)),
            ],
        ),
    ]
